options:
  pex-immobiliare: "Immobiliare"


mysql:
  active: false
  host: localhost
  port: 3306
  database: database
  username: root
  password: root

guis:
  pagination:
    next-page: "Pagina successiva"
    previous-page: "Pagina precedente"
    back: "Indietro"
  immobili:
    titolo-gui: "&cImmobili"
    items:
      tipo-generico:
        material: "BOOK"
        custom-model-data: 0
        display: "&c%tipo%"
        lore:
          - "&7Clicca per visualizzare tutti gli immobili disponibili di questo tipo"
          - "Ci sono: %numero-immobili%"
  tipo-gui:
    titolo-gui: "&c%tipo%"
    items:
      immobile-generico:
        material: "BOOK"
        custom-model-data: 0
        display: "&c%nome_immobile%"
        lore:
          - "Prezzo: &c%prezzo%"
          - "&7Clicca per ottenere la chiave di questo immobile"
  confirmation:
    titolo-gui: "&cConferma"
    items:
      conferma:
        material: "PAPER"
        custom-model-data: 0
        display: "&cAccetta e paga"
        lore:
          - "&7Clicca per confermare l'acquisto di questo immobile"
          - "&cNome: &c%nome_immobile%"
          - "&cPrezzo: &c%prezzo%"
      annulla:
        material: "PAPER"
        custom-model-data: 0
        display: "&cAnnulla"
        lore:
          - "&7Clicca per annullare l'acquisto di questo immobile"
key:
  material: "TRIPWIRE_HOOK"
  custom-model-data: 0
  display: "&cChiave %nome_immobile%"
  lore:
    - "&7Mantieni la chiave nell'inventario per entrare nell'immobile"
  add-lore-owner-when-bought: true
  owner-lore: "&7Proprietario: &c%proprietario%"




messages:
  player-only: "Questo comando è disponibile solo per i giocatori"
  no-permission: "Non hai il permesso di vendere questo immobile"
  property:
    alredy-exists: "Questo immobile è già presente nel database" #placeholders : %nome% %tipo%
    invalid-price: "Il prezzo inserito non è valido"
    bought: "Hai acquistato %nome% per %prezzo% "
    sold: "Hai venduto %nome% per %prezzo% "
    sale-cancelled: "L'acquirente ha annullato l'acquisto"
    not-owner: "Non sei il proprietario di questo immobile"
  region:
    not-exists: "Questa regione non esiste"
    alredy-linked: "Questa regione è già collegata ad un immobile"
  key:
    inventory-full: "Il tuo inventario è pieno"
  not-enough-money: "Non hai abbastanza soldi"
  await-confirmation: "&cIn attesa di conferma"




